#create a program of table by userinput(f"{}")
num=int(input("Enter the Number:"))
print("table of",num)
print(f"{num}*1={num}")
print(f"{num}*2={num}")
print(f"{num}*3={num}")
print(f"{num}*4={num}")
print(f"{num}*5={num}")
print(f"{num}*6={num}")
print(f"{num}*7={num}")
print(f"{num}*8={num}")
print(f"{num}*9={num}")
print(f"{num}*10={num}")